"""Report persistence: Markdown + JSON artifacts, ``report/index.json`` and the
append-only push log that records every email delivery.

Layout::

    report/
      index.json                 # all runs, newest first (the push record ledger)
      push-log.jsonl             # append-only delivery audit
      latest/<topic>.md          # convenience pointer to the newest report
      2026/10/02-vla.md          # dated report
      2026/10/02-vla.json        # full structured record (with references)
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

from .engine import ResearchResult
from .util import date_stamp, now_utc, truncate

log = logging.getLogger(__name__)


def _report_dir(home: Path, cfg: Any) -> Path:
    return home / str(cfg.report.dir)


def report_paths(home: Path, cfg: Any, result: ResearchResult) -> tuple[Path, Path]:
    base = _report_dir(home, cfg)
    date = date_stamp()
    parts = date.split("-")
    dated_dir = base / parts[0] / parts[1]
    stem = f"{date}-{result.topic}"
    return dated_dir / f"{stem}.md", dated_dir / f"{stem}.json"


def ensure_footer(result: ResearchResult) -> str:
    md = result.report_md.rstrip()
    if "## 参考来源" not in md and "## References" not in md:
        md += "\n\n## 参考来源\n\n"
        for ref in result.references:
            md += f"[{ref['n']}] {ref['title']} — {ref['url']}\n"
    md += (
        "\n\n---\n\n"
        f"*Generated by research-bot · topic=`{result.topic}` · depth=`{result.depth}` · "
        f"rounds={result.rounds} · engines={', '.join(result.engines)} · "
        f"skills={', '.join(result.skills)} · model=`{result.models.get('primary', '')}` · "
        f"sources={len(result.references)} · duration={result.duration_s:.0f}s · {result.finished_at}*\n"
    )
    return md


def update_index(home: Path, cfg: Any, record: dict[str, Any]) -> list[dict[str, Any]]:
    index_path = _report_dir(home, cfg) / "index.json"
    index: list[dict[str, Any]] = []
    if index_path.is_file():
        try:
            index = json.loads(index_path.read_text(encoding="utf-8"))
            if not isinstance(index, list):
                index = []
        except json.JSONDecodeError:
            log.warning("index.json is corrupt; starting a fresh index")
            index = []
    index = [r for r in index if r.get("id") != record.get("id")]
    index.insert(0, record)
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return index


def append_push_log(home: Path, cfg: Any, record: dict[str, Any]) -> None:
    log_path = _report_dir(home, cfg) / "push-log.jsonl"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record, ensure_ascii=False) + "\n")


def save_report(home: Path, cfg: Any, result: ResearchResult, *, run_meta: dict[str, Any] | None = None) -> tuple[dict[str, Any], Path]:
    """Persist report artifacts and return ``(index_record, markdown_path)``."""
    md_path, json_path = report_paths(home, cfg, result)
    md_path.parent.mkdir(parents=True, exist_ok=True)

    result.report_md = ensure_footer(result)
    md_path.write_text(result.report_md, encoding="utf-8")

    formats = set(cfg.report.formats or ["md", "json"])
    if "json" in formats:
        payload = result.to_dict(include_sources=bool(cfg.report.include_raw_sources))
        payload["paths"] = {
            "markdown": str(md_path.relative_to(home)),
            "json": str(json_path.relative_to(home)),
        }
        json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if cfg.report.keep_latest:
        latest = _report_dir(home, cfg) / "latest" / f"{result.topic}.md"
        latest.parent.mkdir(parents=True, exist_ok=True)
        latest.write_text(result.report_md, encoding="utf-8")

    findings = sum(len(s.extraction.get("findings") or []) for s in result.subquestions)
    record: dict[str, Any] = {
        "id": f"{date_stamp()}-{result.topic}",
        "date": date_stamp(),
        "timestamp": now_utc().replace(microsecond=0).isoformat(),
        "topic": result.topic,
        "title": result.title,
        "query": result.query,
        "depth": result.depth,
        "rounds": result.rounds,
        "language": result.language,
        "model": result.models.get("primary", ""),
        "engines": result.engines,
        "skills": result.skills,
        "subquestions": len(result.subquestions),
        "findings": findings,
        "sources": len(result.references),
        "duration_s": round(result.duration_s, 1),
        "report_path": str(md_path.relative_to(home)),
        "json_path": str(json_path.relative_to(home)),
        "summary": truncate(result.plan.get("summary", ""), 400),
        "email": {"sent": False, "to": [], "ts": None, "error": None},
        "git": (run_meta or {}).get("git", {}),
        "run_url": (run_meta or {}).get("run_url", ""),
    }
    update_index(home, cfg, record)
    return record, md_path


def record_email(home: Path, cfg: Any, record: dict[str, Any], email_result: dict[str, Any]) -> dict[str, Any]:
    record = dict(record)
    record["email"] = email_result
    update_index(home, cfg, record)
    append_push_log(
        home,
        cfg,
        {
            "ts": now_utc().replace(microsecond=0).isoformat(),
            "id": record.get("id"),
            "topic": record.get("topic"),
            "report_path": record.get("report_path"),
            "email": email_result,
        },
    )
    return record


def load_index(home: Path, cfg: Any) -> list[dict[str, Any]]:
    index_path = _report_dir(home, cfg) / "index.json"
    if not index_path.is_file():
        return []
    try:
        data = json.loads(index_path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else []
    except json.JSONDecodeError:
        return []


def git_metadata(home: Path) -> dict[str, str]:
    """Best-effort git commit + CI run URL for the record."""
    meta: dict[str, str] = {}
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    run_id = os.environ.get("GITHUB_RUN_ID", "")
    if repo and run_id:
        meta["run_url"] = f"{server}/{repo}/actions/runs/{run_id}"
    try:
        import subprocess

        commit = subprocess.run(
            ["git", "-C", str(home), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        ).stdout.strip()
        if commit:
            meta["commit"] = commit
    except Exception:  # noqa: BLE001
        pass
    return meta
